apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: namespace
  labels:
    app: myapp
    type: back-end
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80

    - name: log-agent
      image: logstash
