apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: namespace
  labels:
    app: myapp
    tier: back-end
spec:
  containers:
    - name: myapp-container
      image: nginx
      imagePullPolicy: IfNotPresent
      command:
        - "sleep"
        - "1000"
  restartPolicy: Always
