apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=
# If a field, such as username, is specified in both data and stringData, the value from stringData is used.
stringData:
  username: administrator
