apiVersion: v1
kind: Service
metadata:
  name: some-service
  namespace: namespace
  labels:
    app: some-app
    type: some-type
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 8080
      nodePort: 30000
  selector:
    app: some-app-label
    type: some-type-label
