apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: namespace
  labels:
    app: myapp
    tier: back-end
spec:
  containers:
    - name: myapp-container
      image: alpine
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh","-c"]
      args: ["shuf -i 0-100 -n 1 >> /opt/number.out;"]
  restartPolicy: Always
