apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: namespace
  labels:
    app: myapp
    type: back-end
spec:
  containers:
    - name: nginx-container
      image: nginx
  restartPolicy: OnFailure
