apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    tier: back-end
spec:
  containers:
    - name: myapp-container
      image: nginx
      imagePullPolicy: IfNotPresent
      command: ["sleep"]
      args: ["10"]
  restartPolicy: Always
