apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-d
  labels:
    app: nginx-app
    type: back-end
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-app
        type: back-end
    spec:
      containers:
        - name: nginx-c
          image: nginx
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: nginx-app
      type: back-end
