apiVersion: v1
kind: Service
metadata:
  name: nginx-s
  labels:
    app: nginx-app
    type: back-end
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30501
  selector:
    app: nginx-app
    type: back-end

