apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: namespace
  labels:
    app: myapp
    type: back-end
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
      readinessProbe:
        httpGet:
          path: /api/ready
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 5
        # by default is 3 attempts
        failureThreshold: 8
