apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: readiness-http
spec:
  containers:
    - name: readiness
      image: k8s.gcr.io/liveness
      args:
        - /server
      ports:
        - name: readiness-port
          containerPort: 8080
          hostPort: 8080

      readinessProbe:
        httpGet:
          path: /is-ready
          port: readiness-port
        failureThreshold: 1
        periodSeconds: 10

      startupProbe:
        httpGet:
          path: /healthz
          port: readiness-port
        failureThreshold: 30
        periodSeconds: 10
