apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: namespace
  labels:
    app: myapp
    tier: back-end
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
        tier: back-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: Exists
                    # The Deployment "myapp-deployment" is invalid: spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values: Forbidden: may not be specified when `operator` is 'Exists' or 'DoesNotExist'
                    # Always STATUS:Pending
#                    values:
#                      - kind-worker2
  selector:
    matchLabels:
      app: myapp
      tier: back-end
