apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    tier: back-end
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: back-end
  template:
    metadata:
      labels:
        tier: back-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    # Always STATUS:Pending
                    operator: Lt
                    values:
                      - kind-worker2
