apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    tier: back-end
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: back-end
  template:
    metadata:
      labels:
        tier: back-end
    spec:
      serviceAccountName: nameServiceaccount
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
