apiVersion: v1
kind: ResourceQuota
metadata:
  name: pods-high
  namespace: namespace
spec:
  hard:
    pods: "10"
    cpu: "1000"
    request.cpu: "4"
    limit.cpu: "10"
    memory: 200Gi
    request.memory: 5Gi
    limit.memory: 10Gi
  scopeSelector:
    matchExpressions:
      - operator: In
        scopeName: PriorityClass
        values: ["high"]
