apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistentVolumeClaim
  namespace: namespace
  labels:
    name: label-name
    type: label-type
    app: label-app
spec:
  storageClassName: storage-class-name
  resources:
    requests:
      storage: 5Gi
