kind: PersistentVolume
apiVersion: v1
metadata:
  name: persistentVolume
  namespace: namespace
  labels:
    name: label-name
    type: label-type
    app: label-app
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/somePath/data"
