kind: PersistentVolume
apiVersion: v1
metadata:
  name: persistentVolume
  namespace: namespace
  labels:
    name: label-name
    type: label-type
    app: label-app
spec:
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadOnlyMany
  awsElasticBlockStore:
    volumeID: volume-id
    fsType: ext4
