apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: namespace
  labels:
    app: postgres
data:
  POSTGRES_DB: quarkus-user-service-db
  POSTGRES_USER: developer
  POSTGRES_PASSWORD: strong_password
